# Jekyll Defaults
title: Vinh-Thuyen  
description: A penguin loves computers.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://ntvthuyen.github.io/"
github: http://github.com/ntvthuyen
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
